
language: node_js

node_js:
    - "7"

sudo: false

cache: npm

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.21.3
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install

script:
  - ng build --prod

deploy:
  provider: heroku
  api_key:
    secure: Uo7+DsqI3Taf5/nvspQsK9OF6LH16E3pqZPxkl8D+1z+hCsKSBrvWCyW9PbyeCTCAlF7+hw43Yt33SJAHFKroDfd2jqodgvStNqzvFS27Tv/CMt99o2ZSDG4cK45VsVRG7ctScDU9pRpPbfvtKZ+KASxN3kIlXGnMccYIw0nXIeKPgPcRoRWBBcsi62tfcSOSKMLNqm6KLcRlSTlb892rErqb6jLabujsE+MHBF78xaVqazsLnN9taWSukXSbL5ugfwTZe9HWuxoKk9CHiTmnF4LchtwvdoODEqYr6I93Qqrycr54asR5RZa4H3pET4ZmAdvEtpUdFR1gzpKC2qix8j/We9yUKSUxRKp/Ge2VEO+Ooc2AA/AIjB3U3MPF5k7LU9QVVAVutQXlhWYHurcz1jyxJe5062fch/TrWyFFxIp+Z11eNMXKhNOIhyre1JCDPtupLgEoSr7x77sxEzW2AX5vNnUCmtDSrKMD4AzO1cU+xEKiu5i/yoRftHNRcY4wcXkNWqzQ8/6vy7Z5FW2yCUPfiRYdo6Ld0uXw9AgVXCyz+eyliyLDcf0T2cahrnRAykWkKgQ9mp6akIwsfzaQl88OX2mg/9S/TxaJQpDrNYvN8m5Cf8JPCp+zYxzdbFFzCr2EM9fJ9MB0/Vhm1aajsaxwGLN44zhTXNTYxtk0eY=
  app: oedc
  on:
    repo: alialdemir/oedc
