language: node_js

node_js:
  - "7"

sudo: false

cache: yarn

before_install:NPM 
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.21.3

script:
  - yarn run test:ci

after_success:
  - codecov

before_deploy:
  - yarn run build
  - cp ./dist/index.html ./dist/200.html

deploy:
  provider: surge
  project: ./dist/
  domain: oedc
  skip_cleanup: true