language: node_js

node_js:
    - "7"

sudo: false

cache: npm

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.21.3
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  -   npm install -g @angular/cli
  - cp ./dist/index.html ./dist/200.html

script:
  - npm run test:ci
  - ng build --prod

deploy:
  provider: surge
  project: ./dist/
  domain: oedc.surge.sh
  skip_cleanup: true

  