language: node_js

node_js:
    - "7"

sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.21.3
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g @angular/cli

script:
  - npm run test:ci

before_script:
  - npm run build --prod
  - cp ./dist/index.html ./dist/200.html

deploy:
  provider: surge
  project: ./dist/
  domain: oedc.surge.sh
  skip_cleanup: true
