language: node_js
node_js:
- '7'
sudo: false
cache: npm
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.21.3
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install
script:
- ng build --prod
deploy:
  provider: heroku
  api_key:
    secure: ECdHjsIuk3DeRGW3bycPy2uqeBxvEax1kQbyGaZ4fUmvqRIS/ARfOu3QoLWXajlyI6bQKSAYSMvsRaFNwLETE7rAqNS+ND995d7GuSprvfelPwKo0ECTnfpMuc4ssJ+FBs7/T80xVmIERZmGn+EwxPMZx6CaDf5w9o/5yBBa/Jaeshukz0koa87NOizNFhOFadqlXy/pWjiCZlHEmQoD1gcec/BGItkyWpv1AWsEVSlC+Tap/jcYQcNDts1+//DQ/h/GSIN5l4ZDFuPqQWH6Ju+ZVtwOSIYvwoX4FTbFnhhJzSVwAGnUFpYScllHWOUzjXCI68JGwQFwT5+IzZ2XV0qY7GDaKTCn/nCsi10oncpft0WKrZmbLfo4kMwkyx3xHxCRneSN7zohxfan2xSqHSHDSempYtFFnb/QId9dhZA41olEEwnnBzfsH/ZtsvjdNOlKkF7RM+ihWF3rx/DEgFKlXNWGSShIUsw+QXLZ67eV0+pxunkdTZKJDPDdKVHw4oqmrx4ePadkg21cQUTnYn7uhGwrHBYlGDrPRbIEoOKhQN/4crjuI3JHqfqqg5ILirCdNn++McboJf7TruopGh8pkZq2TCtpzx843lUYOnUpXFhRb9fDn4/L84E3byqPq0ZvAqac+wrbl96DC310+7fVtAuSpH1s8ORXNNOJQbo=
  app: fathomless-badlands-91659
  on:
    repo: alialdemir/oedc
