language: node_js

node_js:
    - "7"

sudo: false

script: node_modules/karma/bin/karma start my.conf.js --single-run

before_install:
    - npm install -g @angular/cli
    - export CHROME_BIN=chromium-browser

before_script:
  - npm run build --prod
  - cp ./dist/index.html ./dist/200.html

deploy:
  provider: surge
  project: ./dist/
  domain: oedc.surge.sh
  skip_cleanup: true
