language: node_js

node_js:
  - "7"

sudo: false

cache: npm

before_deploy:
  - npm run build
  - cp ./dist/index.html ./dist/200.html

deploy:
  provider: surge
  project: ./dist/
  domain: oedc
  skip_cleanup: true