language: node_js

node_js:
    - "0.10"

sudo: false

script: node_modules/karma/bin/karma start config/karma.conf.js --single-run

before_install:
    - npm install -g @angular/cli
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

before_script:
  - npm run build --prod
  - cp ./dist/index.html ./dist/200.html

deploy:
  provider: surge
  project: ./dist/
  domain: oedc.surge.sh
  skip_cleanup: true
